### ISSUE TITLE
ucsd roi

### ISSUE THREAD

**Issue by jiezishu737** [BigTeacher-xyx/DA-Net#2]

**Comment by jiezishu737** [comment]
when i test on worldexpo'10 dataset, i donot know whether sum all the density_map to get the et_count nor sum the density_map roi to get the et_count?
if sum the density_map roi to get the et_count, how to add the roi on the density_map?
thanks

**Comment by BigTeacher-777** [comment]
Multiply the roi and the density map before you sum up

**Comment by sumit2k4** [comment]
Sorry if my question is too basic.
I got 100 GT and 100 ET values but my doubt is how do we calculate the head count from it?
